### ISSUE TITLE
Refactor getWinnerNamesFromList (Sleep.js)

### ISSUE THREAD

**Issue by brycemara** [brycemara/refactor-tractor#40]
Need to refactor to SRP. It's doing too many things.

**Comment by brycemara** [comment]
![Screen Shot 2020-10-27 at 10 10 15 AM](https://user-images.githubusercontent.com/68242949/97321230-a62cf280-183c-11eb-9471-ee5ac92ecac5.png)

**Comment by coopterrones** [comment]
LGTM!
